project:
  type: website

website:
  title: "{{< var course.title >}}"
  favicon: "_assets/favicons/favicon.ico"
  image: "_assets/favicons/favicon-32x32.png"
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true

  search:
    show-item-context: true
    type: overlay
    copy-button: true

  page-footer:
    center:
      - text: "About"
        href: about/this-site.qmd

  navbar:
    logo: "_assets/icon-darkbg.svg"
    left:
      - index.qmd
      - text: "Syllabus"
        href: about/syllabus.qmd
      - text: "Lectures"
        href: topics/all-lectures.qmd
      - text: "Practice"
        href: practice/all-exos.qmd
  sidebar:
    style: "docked"
    align: left
    contents: 
      - section: "Course Notes"
        contents: 
        - section: "Hardware"
          contents: 
          - topics/hardware/introduction-to-computers.qmd
          - topics/hardware/external-components.qmd
          - topics/hardware/internal-components.qmd  
          - topics/hardware/understanding-cpus.qmd
          - href: topics/hardware/chips_ram_cpu.pdf.pdf
            text: "Chipets, CPU and RAM" # This will open the PDF in a new tab/window
          - topics/hardware/bios_cmos_uefi.qmd
          
        - section: "Data representation"
          contents:
          - topics/data-representation/introduction-to-binary.qmd
          - topics/data-representation/logic-gates-and-boolean-algebra.qmd
          - topics/data-representation/binary-math.qmd   
          - topics/data-representation/text-in-computers.qmd
          - topics/data-representation/hexadecimal-numbers.qmd

        - section: "Operating Systems"
          contents:
          - topics/operating-systems/operating-system-intro.qmd
          - topics/operating-systems/operating-system-install.qmd
          - topics/operating-systems/operating-systems-details.qmd
          - href: topics/operating-systems/disk_partitions_file_systems.pdf
            text: "Disk and File Systems" # This will open the PDF in a new tab/window

format:
  html:
    css: _assets/css/styles.css
    toc: true
    toc-depth: 4
    grid:
          sidebar-width: 250px # Adjust this value as desired
    toc-title: Contents
    date-modified: last-modified
    highlight-style: a11y
    theme: 
      dark: darkly
      light: flatly
    margin-left: 1em
    margin-right: 1em
    margin-top: 1em
    margin-bottom: 1em
    linestretch: 1.7
    lightbox:
      match: auto
      effect: fade
      loop: true
    copyright:
      holder: Michael Haaf
      year: 2025
    license: CC BY-NC-SA
